version: "3.8"

services:
  # Node.js API - Direct exposure
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-rest-api-prod
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      # Performance tuning
      - NODE_OPTIONS=--max-old-space-size=1024
      - UV_THREADPOOL_SIZE=128
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
        reservations:
          memory: 256M
          cpus: "0.5"
    # Health check
    # healthcheck:
    #   test: ["CMD", "node", "healthcheck.js"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
